name: Build and deploy SAM template

on:
  workflow_call:
    secrets:
      PAT_GITHUB:
        required: true
      AWS_DEV_OIDC_ROLE_ARN:
        required: true
      AWS_QA_OIDC_ROLE_ARN:
        required: true
      AWS_UAT_OIDC_ROLE_ARN:
        required: true
    inputs:
      DEV_TOML_CONFIG:
        required: false
        default: dev
        type: string
      QA_TOML_CONFIG:
        required: false
        default: qa
        type: string
      UAT_TOML_CONFIG:
        required: false
        default: uat
        type: string
      TOML_CONFIG_FILE:
        required: false
        default: samconfig.toml
        type: string
      TEMPLATE_NAME:
        required: false
        default: template.yaml
        type: string
      PYTHON_VERSION:
        type: string
        default: '3.8'
        required: false
      ARM_SUPPORT:
        type: boolean
        default: false
        required: false

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: Configure AWS credentials for DEV
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEV_OIDC_ROLE_ARN }}
          role-session-name: samplerolesession
          aws-region: us-east-2
      - name: Settings to support ARM Build
        if: ${{ inputs.ARM_SUPPORT }}
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Validate template
        run: sam validate --template-file ${{ inputs.TEMPLATE_NAME }}
      - name: Inject GithubToken into samconfig (if present)
        run: |
          if grep -q 'GithubToken="\$GITHUB_TOKEN"' "${{ inputs.TOML_CONFIG_FILE }}"; then
            sed -i "s|GithubToken=\"\$GITHUB_TOKEN\"|GithubToken=\"${GITHUB_TOKEN}\"|g" "${{ inputs.TOML_CONFIG_FILE }}"
          fi
      - name: Build SAM
        run: sam build --template-file ${{ inputs.TEMPLATE_NAME }} --use-container -p --config-file ${{ inputs.TOML_CONFIG_FILE }} --config-env ${{ inputs.DEV_TOML_CONFIG }} --container-env-var GITHUB_TOKEN=$GITHUB_TOKEN
      - name: Deploy SAM template
        run: sam deploy --config-file ${{ inputs.TOML_CONFIG_FILE }} --config-env ${{ inputs.DEV_TOML_CONFIG }} --capabilities CAPABILITY_NAMED_IAM --no-confirm-changeset --no-fail-on-empty-changeset --resolve-image-repos
  deploy-qa:
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    if: ${{ needs.deploy-dev.result == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: Configure AWS credentials for QA
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_QA_OIDC_ROLE_ARN }}
          role-session-name: samplerolesession
          aws-region: us-east-2
      - name: Settings to support ARM Build
        if: ${{ inputs.ARM_SUPPORT }}
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Validate template
        run: sam validate --template-file ${{ inputs.TEMPLATE_NAME }}
      - name: Inject GithubToken into samconfig (if present)
        run: |
          if grep -q 'GithubToken="\$GITHUB_TOKEN"' "${{ inputs.TOML_CONFIG_FILE }}"; then
            sed -i "s|GithubToken=\"\$GITHUB_TOKEN\"|GithubToken=\"${GITHUB_TOKEN}\"|g" "${{ inputs.TOML_CONFIG_FILE }}"
          fi
      - name: Build SAM
        run: sam build --template-file ${{ inputs.TEMPLATE_NAME }} --use-container -p --config-file ${{ inputs.TOML_CONFIG_FILE }} --config-env ${{ inputs.QA_TOML_CONFIG }} --container-env-var GITHUB_TOKEN=$GITHUB_TOKEN
      - name: Deploy SAM template
        run: sam deploy --config-file ${{ inputs.TOML_CONFIG_FILE }} --config-env ${{ inputs.QA_TOML_CONFIG }} --capabilities CAPABILITY_NAMED_IAM --no-confirm-changeset --no-fail-on-empty-changeset --resolve-image-repos
  deploy-uat:
    runs-on: ubuntu-latest
    needs: [deploy-qa]
    if: ${{ needs.deploy-qa.result == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: Configure AWS credentials for UAT
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_UAT_OIDC_ROLE_ARN }}
          role-session-name: samplerolesession
          aws-region: us-east-2
      - name: Settings to support ARM Build
        if: ${{ inputs.ARM_SUPPORT }}
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Validate template
        run: sam validate --template-file ${{ inputs.TEMPLATE_NAME }}
      - name: Inject GithubToken into samconfig (if present)
        run: |
          if grep -q 'GithubToken="\$GITHUB_TOKEN"' "${{ inputs.TOML_CONFIG_FILE }}"; then
            sed -i "s|GithubToken=\"\$GITHUB_TOKEN\"|GithubToken=\"${GITHUB_TOKEN}\"|g" "${{ inputs.TOML_CONFIG_FILE }}"
          fi
      - name: Build SAM
        run: sam build --template-file ${{ inputs.TEMPLATE_NAME }} --use-container -p --config-file ${{ inputs.TOML_CONFIG_FILE }} --config-env ${{ inputs.UAT_TOML_CONFIG }} --container-env-var GITHUB_TOKEN=$GITHUB_TOKEN
      - name: Deploy SAM template
        run: sam deploy --config-file ${{ inputs.TOML_CONFIG_FILE }} --config-env ${{ inputs.UAT_TOML_CONFIG }} --capabilities CAPABILITY_NAMED_IAM --no-confirm-changeset --no-fail-on-empty-changeset --resolve-image-repos
